language: c
sudo: require
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - OCAML_VERSION=4.04.2
    - DISTRO=debian-stable
    - PACKAGE=xapi-nbd
    - PINS="nbd:git://github.com/xapi-project/nbd.git#bugfix-v2.x"
    - TESTS=false
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
  fast_finish: true
  allow_failures:
    - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
